spring:
  application:
    name: ToDoApplication

  datasource:
    url: jdbc:postgresql://localhost:5432/todoapplication
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

todoapplication:
  security:
    secret: "palavrasecreta"